#!/bin/bash

echo "HELLO WORLD!"
set -x
set -e

if [ ! -f /etc/mlab/bootstrap-functions ] ; then
    echo "ERROR: missing bootstrap-functions"
    exit 1
fi

source /etc/mlab/bootstrap-functions
source $PWD/etc/slice-functions

function setup_rsync () {
    slicename=$1
    if has_private_ip ; then
        port=7999
    else
        port=`python -c "print 7999+sum([ ord(c) for c in '$slicename' ])"`
    fi
    if [ -f etc/rsyncd.conf ] ; then
        sed -e 's/SLICENAME/'$slicename'/g' \
            -e 's/PORT/'$port'/g' etc/rsyncd.conf > /etc/rsyncd.conf
    fi
    mkdir -p /var/spool/$slicename
}

slicename=$( get_slice_name )
setup_rsync $slicename

install_file etc/slice-functions /etc/
install_file bin/slice-recreate  /usr/bin/
install_file bin/slice-restart   /usr/bin/
install_file init.d/slicectrl-functions    /etc/init.d/
install_file init.d/slicectrl /etc/init.d/

/sbin/chkconfig slicectrl on

assert_dir "/etc/cron.hourly"
cat <<\EOF > /etc/cron.hourly/update-experiment.sh
#!/bin/bash
set -x
set -e
echo "RUNNING update-experiment.sh"
if [ ! -f /etc/mlab/bootstrap-functions ] ; then
    echo "ERROR: missing bootstrap-functions"
    exit 1
fi
source /etc/mlab/bootstrap-functions
source /etc/slice-functions
slicename=$( get_slice_name )

if [ $UID -eq "0" ] ; then
    su - $slicename -c "$0"
else
    PACKAGE_SLICE=$( get_url_for_file slice-packages/$slicename.tar.gz )
    PREFIX=/home/$slicename
    update $PACKAGE_SLICE
fi
EOF

chmod 755 /etc/cron.hourly/update-experiment.sh
/etc/cron.hourly/update-experiment.sh
