#!/bin/bash

set -x
set -e

source $PWD/etc/slice-functions

function setup_rsync () {
    slicename=$1
    if has_private_ip ; then
        port=7999
    else
        port=`python -c "print 7999+sum([ ord(c) for c in '$slicename' ])"`
    fi
    if [ -f etc/rsyncd.conf ] ; then
        sed -e 's/SLICENAME/'$slicename'/g' \
            -e 's/PORT/'$port'/g' etc/rsyncd.conf > /etc/rsyncd.conf
    fi
    mkdir -p /var/spool/$slicename
}

setup_rsync $SLICENAME
assert_dir "/etc/cron.hourly"

install_file etc/cron.hourly/update-experiment.sh /etc/cron.hourly/
install_file etc/slice-functions        /etc/
install_file bin/slice-recreate         /usr/bin/
install_file bin/slice-restart          /usr/bin/
install_file init.d/slicectrl-functions /etc/init.d/
install_file init.d/slicectrl           /etc/init.d/

/sbin/chkconfig slicectrl on
mkdir -p /var/run/$SLICENAME

mkdir -p /opt/slice/
chmod 755 /opt/slice/
chown $SLICENAME:slices /opt/slice/

# NOTE: change /home/$SLICENAME into a link to /opt/slice/
# This will allow user-privileged management of package updates.
mv /home/$SLICENAME /opt/slice/current
ln -s /opt/slice/current /home/$SLICENAME

chmod 755 /etc/cron.hourly/update-experiment.sh
if [ ! -d /home/$SLICENAME/current ] ; then
    /etc/cron.hourly/update-experiment.sh
    /sbin/service slicectrl start
fi
