#!/bin/bash

# NOTE: 'install' should be idempotent.  
# i.e. running multiple times should be safe
set -x
set -e

echo "SLICE EXAMPLE INSTALL!!"
echo $PWD

if [ ! -x /usr/sbin/lighttpd ] ; then
    sudo yum install -y lighttpd
    sudo yum install -y vim
fi

if [ ! -f /etc/lighttpd/lighttpd.conf ] || \
   [ ! -f /usr/sbin/lighttpd ] ; then
    echo "Error: cannot continue"
    exit 1
fi

sudo mkdir  -p /var/log/pathchirp
sudo chmod 777 /var/log/pathchirp

PATTERN="^#server.port.*= 81$"
if sudo grep -q "$PATTERN" /etc/lighttpd/lighttpd.conf ; then
    sudo sed -i -e "s/$PATTERN/server.port = 8088/g" /etc/lighttpd/lighttpd.conf
fi

