#!/bin/bash

# NOTE: 'install' should be idempotent.  
# i.e. running multiple times should be safe
set -x
set -e

echo "SLICE EXAMPLE INSTALL!!"
echo $PWD

if [ ! -x /usr/sbin/httpd ] ; then
    sudo yum install -y httpd
    sudo yum install -y vim
fi

if [ ! -f /etc/httpd/conf/httpd.conf ] ; then
    echo "Error: cannot continue"
    exit 1
fi

PATTERN="^Listen 80$"
if grep -q "$PATTERN" /etc/httpd/conf/httpd.conf ; then
    sudo sed -i -e "s/$PATTERN/Listen 8088/g" /etc/httpd/conf/httpd.conf
fi

