#!/bin/bash

source /etc/slice-functions
echo "Starting service"

sudo /sbin/service lighttpd start
$SLICEHOME/bin/pathchirp_rcv &> /var/log/pathchirp/rcv.log &
$SLICEHOME/bin/pathchirp_snd &> /var/log/pathchirp/snd.log &

exit $?
