#!/bin/bash

source /etc/slice-functions
echo "Stopping service"

sudo /sbin/service lighttpd stop
if pgrep -f "pathchirp_rcv|pathchirp_snd" > /dev/null ; then
    pkill -f pathchirp_rcv
    pkill -f pathchirp_snd
fi

exit $?
