#!/bin/bash

function get_slice_ipv4() {
	## NOTE: this call should call out to vsys to get an authoritative list of
	## IPs assigned to this slice in /etc/vservers/interfaces/*/addr
	IP=`/sbin/ip -o -f inet addr show  | awk '{print $4}' | sed -e 's/\/26//g'`
	echo $IP
}

function get_slice_ipv6() {
	IP=`/sbin/ip -o -f inet6 addr show  | awk '{print $4}' | sed -e 's/\/64//g'`
	echo $IP
}

function has_private_ip() {
    l=`ifconfig | grep eth0 | wc -l`
    if [ $l -gt 1 ] ; then
        return 0
    elif [ $l -eq 1 ] ; then
        return 0
    else
        echo "HAS NO IP!"
        return 1
    fi
}

function get_site_name() {
	SITE=$( hostname | tr 'a-z' 'A-Z' | awk -F. '{print $2}' )
	echo $SITE
}

# vsudo <cmd> ...
